# Java
## 2022-01-08 Sat

### 에러, 예외
* 에러는 크게 두 종류로 나뉜다.
  1. 컴파일 에러: 컴파일 단계에서 발생하는 에러
  2. 런타임 에러: 컴파일은 성공했지만, App.의 실행 도중 발생하는 에러
* 이 중 런타임 에러는 다시 에러와 예외로 나뉜다.
  1. 에러: App.에 작성한 코드에 의해 조치될 수 없는 오류
  2. 예외: 개발자의 적절한 코드 구현을 통해 비정상적인 App.의 종료를 막을 수 있는 오류
* Java에서는 런타임 에러 또한 각각 Error와 Exception 클래스로 정의해두었다.
  * 이 때, 둘 모두 Object 클래스를 상속받는다.

### Exception, RuntimeException
* 모든 '예외'의 최고 조상 클래스이며, 크게 다음과 같은 두 종류로 나뉜다.
  1. Exception 클래스 및 자식 클래스들
  2. RuntimeException 클래스 및 자식 클래스들
    * RuntimeException 역시 Exception의 자식이지만, 편의상 이렇게 분류하였다.
* RuntimeException 클래스들은 주로 개발자의 실수에 의해 발생되는 예외이다.
  * 예를 들어 0 나누기 예외가 있다.
* Exception 클래스들은 주로 외부의 영향으로 발생하는 예외이며, 사용자들의 동작에 의해 발생하는 경우가 많다.
  * 예를 들어 FileNotFoundException 등 파일을 찾지 못하거나, 입력 데이터 형식이 잘못 된 경우가 있다.

### 예외 처리
* 예외 처리는 App. 실행 중 발생할 수 있는 예외에 대비하는 코드를 작성하는 것을 말한다.
* 적절한 예외 처리는 예외가 발생하더라도 App.을 종료시키지 않고, 계속해서 실행되도록 한다.
* 예외 처리되지 않은 예외는 uncaught exception으로서 JVM의 예외 처리기(UncaughtExceptionHandler)가 처리한 후 화면에 원인을 출력한다.
* 예외 처리를 위한 코드는 다음과 같은 형식을 사용한다.
```
try {
} catch (Exception e) {
}
```
* 하나의 try에는 여러 종류의 예외를 처리할 수 있도록 하나 이상의 catch 블록이 자리할 수 있다.
* 이 때, 발생한 예외의 종류와 ㅊ일치하는 단 하나의 catch 문만이 실행된다.
  * break가 없는 switch문처럼 동작하지는 않는다는 의미이다. catch는 최대 하나만 실행된다!
* 발생한 예외와 일치하는 catch 블록이 없다면 예외는 처리되지 않는다.
* try 블록 또는 catch 블록 내부에서도 예외가 발생할 수 있으므로, 별도의 try - catch 문을 포함하도록 작성할 수 있다.
* try 블록 내부에서 예외가 발생하면, 발생한 예외와 일치하는 예외를 처리하는 catch 블록을 찾는다.
  * 있으면, 해당 catch 블록의 코드를 수행한다.
  * 없으면, 해당 예외는 처리되지 못한다.
  * 예외가 발생한 시점에서 try 문을 벗어나므로, try 블록에서 예외가 발생한 직후의 코드부터는 실행되지 않는다.
      * 때문에 try 블록에 포함시킬 코드의 범위를 적절히 결정지을 수 있어야 한다.
